services:
  ics-is-redis:
    container_name: ics-is-redis
    image: redis:7.4-bookworm
    command:
      - "bash"
      - "-c"
      - "redis-server --maxmemory 1073741824 --maxmemory-policy volatile-lru"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  ics-is-worker:
    image: ${REGISTRY_PATH}ics-is-worker
    build:
      dockerfile: worker.Dockerfile
    volumes:
      - ics-is-data:/data
    command: rq worker -u redis://ics-is-redis:6379 default
    environment:
      REDIS_HOST: ics-is-redis
      IS_DATA_DIR: /data
    deploy:
      replicas: 3
    depends_on:
      - ics-is-redis

  ics-is-backend:
    image:  ${REGISTRY_PATH}ics-is-backend
    container_name: ics-is-backend
    build:
      dockerfile: backend.Dockerfile
    volumes:
      - ics-is-data:/data
    command: uvicorn ics_components.main:app --port 9999 --app-dir src --host 0.0.0.0
    environment:
      REDIS_HOST: ics-is-redis
      IS_DATA_DIR: /data
    ports:
      - 9999:9999
    depends_on:
      - ics-is-redis

volumes:
  ics-is-data:



