services:
  ics-is-redis:
    container_name: ics-is-redis
    image: redis:7.4-bookworm
    command:
      - "bash"
      - "-c"
      - "redis-server --maxmemory 1073741824 --maxmemory-policy volatile-lru"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - 6379:6379

  ics-is-worker:
    build:
      dockerfile: worker.Dockerfile
    volumes:
      - ./src:/app/src
      - ./lib:/app/lib
      - ics-is-data:/data
    command: rq worker -u redis://ics-is-redis:6379 default
    environment:
      REDIS_HOST: ics-is-redis
      IS_DATA_DIR: /data
    deploy:
      replicas: 3
    depends_on:
      - ics-is-redis

  ics-is-backend:
    container_name: ics-is-backend
    build:
      dockerfile: backend.Dockerfile
    volumes:
      - ./src:/app/src
      - ./lib:/app/lib
      - ics-is-data:/data
    command: uvicorn lib.ics_components.src.main:app --port 9999 --reload --app-dir src --host 0.0.0.0
    environment:
      REDIS_HOST: ics-is-redis
      IS_DATA_DIR: /data
    ports:
      - 9999:9999
#      - 9898:9898 # python debug server
    depends_on:
      - ics-is-redis

  ics-is-rq-dashboard:
    container_name: ics-is-rq-dashboard
    build:
      dockerfile: worker.Dockerfile
    command: rq-dashboard --redis-url=redis://ics-is-redis:6379
    ports:
      - 9181:9181
#    profiles:
#      - dev

volumes:
  ics-is-data:
