### fetch IDs of currently stored SAS models
GET {{server}}/fetchStoredModels

### train a new model based on submitted answer data
POST {{server}}/trainFromAnswers

### predict score of submitted answers
POST {{server}}/predictFromAnswers

### remove all models from service
GET {{server}}/wipe\_models
