# coding: utf-8

"""
    Coding-Service-API

    Coding-Service-API

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TaskTypeInfoInstructionsSchema(BaseModel):
    """
    TaskTypeInfoInstructionsSchema
    """ # noqa: E501
    id: StrictStr = Field(alias="$id")
    the_schema: StrictStr = Field(alias="$schema")
    __properties: ClassVar[List[str]] = ["$id", "$schema"]

    @field_validator('the_schema')
    def _schema_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('http://json-schema.org/draft/2020-12/schema#', 'http://json-schema.org/draft/2019-09/schema#', 'http://json-schema.org/draft-07/schema#'):
            raise ValueError("must be one of enum values ('http://json-schema.org/draft/2020-12/schema#', 'http://json-schema.org/draft/2019-09/schema#', 'http://json-schema.org/draft-07/schema#')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
        "extra": 'allow'
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TaskTypeInfoInstructionsSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TaskTypeInfoInstructionsSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "$id": obj.get("$id"),
            "$schema": obj.get("$schema")
        })
        return _obj


