# coding: utf-8

"""
    Coding-Service-API

    Coding-Service-API

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class TaskAction(str, Enum):
    """
    TaskAction
    """

    """
    allowed enum values
    """
    COMMIT = 'commit'
    ABORT = 'abort'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TaskAction from a JSON string"""
        return cls(json.loads(json_str))


